Spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/springjwtnew_db
#    username: postgres
#    password: postgres
    url: jdbc:mariadb://localhost:3306/springjwtnew_db
    username: root
    password:




  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
